/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import com.fasterxml.jackson.core.type.TypeReference;
import edu.austral.ingsis.clientserver.Message;
import edu.austral.ingsis.clientserver.netty.client.NettyClientBuilder;

import java.net.InetSocketAddress;

public class ClientExample {

    public static void main(String[] args) {


        final var client = NettyClientBuilder.Companion.createDefault()
                .withAddress(new InetSocketAddress("localhost", 8095))
                .withConnectionListener(new MyClientConnectionListener())
                .addMessageListener("ping", new TypeReference<>() {
                }, new PingListener())
                .build();

        client.connect();

        //When the client connects, it sends a "hello" type message with the payload "Hello Server".
        client.send(new Message<>("hello", new HelloPayload("Server")));
    }

}
