/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example;

import com.fasterxml.jackson.core.type.TypeReference;
import edu.austral.ingsis.clientserver.Message;
import edu.austral.ingsis.clientserver.netty.server.NettyServerBuilder;

public class ServerExample {

    public static void main(String[] args) {
        final var server = NettyServerBuilder.Companion.createDefault()
                .withPort(8095)
                .withConnectionListener(new MyServerConnectionListener())
                .addMessageListener("hello", new TypeReference<>() {
                }, new HelloListener()) // se suscribe al topico "hello". Este topico lo usa un client cuando se conecta.
                .build();

        server.start();


        // Every second, the server broadcasts a "ping" message to all connected clients, asking if they are there.
        try {
            while (true) {
                Thread.sleep(1000);
                // server manda al topico "ping" el mensaje "Are you there?". Cualquier cliente subscrito lo va a recibir.
                server.broadcast(new Message<>("ping", "Are you there?"));
            }
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
